docs: added github action to build doxygen documentation
zephyrproject-rtos/zscilib pull request #40
Opened 2022-09-27 06:45 UTC by uLipe

Signed-off-by: Felipe Neves <felipe.neves@linaro.org>

2022-09-27 06:46 UTC, uLipe commented
@microbuilder  @gmarull  PTAL

2022-09-27 08:03 UTC, gmarull approved these changes

2022-09-27 12:58 UTC, microbuilder requested changes
This needs a step to deploy to the `gh-pages` branch (https://github.com/zephyrproject-rtos/zscilib/tree/gh-pages), which causes documentation to be available here: https://zephyrproject-rtos.github.io/zscilib/

EDIT: The push should only happen on a merge, of course!

2022-09-28 16:20 UTC, uLipe commented
@microbuilder PTAL.

Had to make some sligth modifications on the doxyfile, since most of the actions to deploy to github page does not run inside of doc folder, and / or the option working-directory is not available.

2022-09-28 16:39 UTC, microbuilder approved these changes

2022-09-28 16:40 UTC, merged